name: copernicus
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - numpy
  - pydap
  - cartopy
  - matplotlib
  - geemap
  - ipywidgets
  - netCDF4
  - pip
  - pip:
    - lxml
    - cdsapi